run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosimple
    - unused
    - ineffassign
    - typecheck
    - deadcode
    - structcheck
    - varcheck
    - revive
    - gocritic
    - gofmt
    - misspell
    - prealloc
    - unconvert
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - golint
  max-same-issues: 5
  max-issues-per-linter: 0
  new: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true

  staticcheck:
    checks: ["all"]

  revive:
    severity: warning
